name: Docker Image CI

on:
  workflow_run:
    workflows: ["Laravel"]  # Menunggu Workflow 1 selesai
    types:
      - completed  # Bisa juga 'requested' atau 'in_progress'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sipintar:v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: afadillah/sipintar:v1
